export const clothes = [
  {
    id: "1",
    name: "Explorer Sailor Suit",
    price: "29.90",
    limited: "limited",
    stock: "New",
    image: "./src/assets/shopPage/紀念品水手上衣1.jpg",
  },
  {
    id: "2",
    name: "Guardian Sailor Suit",
    price: "29.90",
    limited: "limited",
    stock: "New",
    image: "./src/assets/shopPage/紀念品水手上衣2.jpg",
  },
  {
    id: "3",
    name: "Dream Sailor Suit",
    price: "29.90",
    limited: "limited",
    stock: "New",
    image: "./src/assets/shopPage/紀念品水手上衣3.jpg",
  },
];
export const merch = [
  {
    id: "4",
    name: "OP Cruise Eco-friendly Cup",
    price: "369.90",
    limited: "",
    stock: "New",
    image: "./src/assets/shopPage/紀念品杯.jpg",
  },
  {
    id: "5",
    name: "OP Cruise Special Sailor Cap",
    price: "229.90",
    limited: "",
    stock: "",
    image: "./src/assets/shopPage/紀念品水手帽.jpg",
  },
  {
    id: "6",
    name: "OP Cruise Limited Edition Red Panda Doll",
    price: "174.90",
    limited: "limited",
    stock: "",
    image: "./src/assets/shopPage/紀念品水手衣服動物公仔.jpg",
  },
  {
    id: "7",
    name: "OP Cruise Limited Edition Sea Turtle Doll",
    price: "129.90",
    limited: "limited",
    stock: "Low",
    image: "./src/assets/shopPage/紀念品水手衣服海龜.jpg",
  },
];
export const trinkets = [
  {
    id: "8",
    name: "OP Cruise Special Edition Pocket Watch",
    price: "369.90",
    limited: "",
    stock: "",
    image: "./src/assets/shopPage/trinkets-watch.jpg",
  },
  {
    id: "9",
    name: "OP Cruise Lovers' Bracelets",
    price: "229.90",
    limited: "",
    stock: "New",
    image: "./src/assets/shopPage/trinkets-bracelet.jpg",
  },
  {
    id: "10",
    name: "OP Cruise Limited Edition Key Chain",
    price: "174.90",
    limited: "limited",
    stock: "Low",
    image: "./src/assets/shopPage/海洋公園郵輪限定紀念品鑰匙扣3.jpg",
  },
  {
    id: "11",
    name: "OP Cruise Stickers for Kids",
    price: "129.90",
    limited: "",
    stock: "",
    image: "./src/assets/shopPage/trinkets-sticker.jpg",
  },
];
